version: "3.8"

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-database_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_database_password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PGUSER: ${POSTGRES_USER:-database_user}
      PGPASSWORD: ${POSTGRES_PASSWORD:-your_database_password}
      PGDATABASE: ${POSTGRES_DB:-database}
      PGHOST: ${PGHOST:-database}
      PGPORT: ${PGPORT:-5432}
      DATABASE_URL: ${DATABASE_URL:-postgres://database_user:your_database_password@database:5432/database}
    depends_on:
      - database
    ports:
      - "5001:5001"
    volumes:
      - ./backend/:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5001}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    restart: always

volumes:
  db_data:
